w10d01/coffee-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :coffees

  # resources :origins
  
  resources :origins do
    resources :coffees
  end

end

w10d01/coffee-app/app/models/coffee.rb
class Coffee < ApplicationRecord
  belongs_to :origin
end

w10d01/coffee-app/app/models/origin.rb
class Origin < ApplicationRecord
  has_many :coffees
end

w10d01/coffee-app/app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController

  def index
    @origin = Origin.find params[:origin_id]
    @coffees = @origin.coffees
  end

end

w10d01/coffee-app/app/controllers/origins_controller.rb
class OriginsController < ApplicationController

  def index
    @origins = Origin.all
  end

end

w10d01/coffee-app/app/helpers/coffees_helper.rb
module CoffeesHelper
end

w10d01/coffee-app/app/helpers/origins_helper.rb
module OriginsHelper
end

w10d01/coffee-app/app/views/coffees/index.html.erb
<h2>All the coffees!</h2>
<%= link_to "Origins", origins_path %>

<% @coffees.each do |coffee| %>
  <div class="coffee" style="border: 1px solid black;">
    <h2><%= coffee.blend_name %></h2>
    <h4>Variety: <%= coffee.variety %></h4>
    <h4>Notes: <%= coffee.notes %></h4>
    <h4>Origin: <%= coffee.origin.origin %></h4>
  </div>
<% end %>

w10d01/coffee-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/coffee-app/app/views/origins/index.html.erb
<h2>All the origins!</h2>

<% @origins.each do |origin| %>
  <div class="origin">
    <h2>Origin: <%= origin.origin %></h2>
    <h3><%= link_to "Coffees", origin_coffees_path(origin) %></h3>
  </div>
<% end %>