w10d02/space/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :planets

  # resources :stars

  resources :stars do
    resources :planets
  end

end

w10d02/space/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d02/space/app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :star

  validates :planet_name, presence: true
  validates :star, presence: true
end

w10d02/space/app/models/star.rb
class Star < ApplicationRecord
  has_many :planets
end

w10d02/space/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d02/space/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @star = Star.find(params[:star_id])
    @planets = @star.planets
  end
end

w10d02/space/app/controllers/stars_controller.rb
class StarsController < ApplicationController
  def index
    @stars = Star.all
    # render json: @stars
  end
end

w10d02/space/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d02/space/app/helpers/planets_helper.rb
module PlanetsHelper
end

w10d02/space/app/helpers/stars_helper.rb
module StarsHelper
end

w10d02/space/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Space</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d02/space/app/views/planets/index.html.erb
<h1>All the planets for <%= @star.star_name %>!</h1>

<%= link_to "Stars", stars_path %>

<% @planets.each do |planet| %>
  <div class="planet" style="border: 1px solid salmon;">
    <h2>Name: <%= planet.planet_name %></h2>
    <h2>Moon: <%= planet.moon %></h2>
    <h3>Star: <%= planet.star.star_name %></h3>
  </div>
<% end %>

w10d02/space/app/views/stars/index.html.erb
<h1>All the stars!!</h1>

<% @stars.each do |star| %>
  <div class="star">
    <h2><%= star.star_name %></h2>
    <h3>See the <%= link_to "Planets", star_planets_path(star) %></h3>
  </div>
<% end %>